name: requests_inspector
description: A Flutter package for logging REST-APIs and GraphQL requests and
  accessing it by Shaking your phone to get the RequestsInspector widget on your
  screen.
version: 3.3.1
homepage: https://github.com/Abdelazeem777/requests_inspector

environment:
  sdk: ">=3.5.0"
  flutter: ">=1.20.0"

dependencies:
  collection: ^1.15.0
  dio: ^5.3.3
  flutter:
    sdk: flutter
  gql: ^1.0.0+1
  graphql: ^5.2.1
  graphql_flutter:
#    path: '/Volumes/Data 1/apps/custom_pakages/graph_ql_flutter/packages/graphql_flutter'
    git: 'https://github.com/mohmedelsayed/enhanced_graphql_flutter.git'
  provider: ^6.1.1
  share_plus: ^10.1.4

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
